# Generated by Django 5.2.7 on 2025-10-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sensor_ID', models.IntegerField(null=True)),
                ('Sensor_Name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedestrianCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time', models.CharField(max_length=150)),
                ('Year', models.IntegerField(null=True)),
                ('Month', models.CharField(max_length=150)),
                ('Mdate', models.IntegerField(null=True)),
                ('Day', models.CharField(max_length=150)),
                ('Time', models.IntegerField(null=True)),
                ('Hourly_Counts', models.IntegerField(null=True)),
                ('total_count', models.IntegerField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedestrian_counts', to='ped_counting_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150)),
                ('predicted_count', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ped_counting_app.location')),
            ],
        ),
    ]
